Laba41/Laba41/urls.py
"""
Definition of urls for Laba41.
"""

from datetime import datetime
from django.urls import path
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('link/', views.link, name='link'),
    path('anketa/', views.anketa, name='anketa'),
    path('registration/', views.registration, name='registration'),
    path('blog/', views.blog, name='blog'),
    path('(?P<parametr>\d+)', views.blogpost, name='blogpost'),
    path('newpost/', views.newpost, name='newpost'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Авторизация',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('videopost', views.videopost, name='videopost')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

Laba41/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from .models import Comment
from .models import Blog

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))
class AnketaForm (forms.Form):
    name = forms.CharField (label = 'Ваше имя' , min_length=2 , max_length=100)
    city = forms.CharField (label = 'Ваш Город' , min_length=2 , max_length=100)
    gender = forms.ChoiceField (label = 'Ваш пол' , choices=[('1','Мужской'),('2','Женский')] , widget=forms.RadioSelect, initial=1 )
    notice = forms.BooleanField (label = 'Получать новости о новинка на e-mail ? ' , required=False)
    email = forms.EmailField (label = 'Ваше e-mail' , min_length=7)
    message = forms.CharField (label = 'Отзыв' , widget=forms.Textarea(attrs={'rows':12 ,'cols':20}))
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        labels = {"text": "Комментарий"}

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ("title", "description", "content",)
        labels = {"title": "Заголовок", "description": "Краткое содержание", "content": "Полное содержание"}

Laba41/app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Hobby World Games – это сеть фирменных магазинов, в которых представлен широчайший ассортимент настольных игр. К нам приходят как преданные фанаты этого хобби, так и те, кто только начинает с ним знакомиться.</p>

{% endblock %}

Laba41/app/templates/app/anketa.html
{% extends "app/layout.html" %}
{% block content %}
{% load static %}
{% if form != None %}
    <br /><h2>Отправьте пожалуйста заполненную форму</h2><br/>
      <div>
          <form method="post">
              {% csrf_token %}
              <label for="{{form.name.id_for_label}}"?>{{form.name.label}}:</label>
              {{form.name}}<br /><br />
              <label for="{{form.city.id_for_label}}"?>{{form.city.label}}:</label>
              {{form.city}}<br /><br />
              <label for="{{form.gender.id_for_label}}"?>{{form.gender.label}}:</label>
              {{form.gender}}<br /><br />
              <label for="{{form.notice.id_for_label}}"?>{{form.notice.label}}:</label>
              {{form.notice}}<br /><br />
              <label for="{{form.email.id_for_label}}"?>{{form.email.label}}:</label>
              {{form.email}}<br /><br />
              <label for="{{form.message.id_for_label}}"?>{{form.message.label}}:</label><br />
              {{form.message}}<br /><br />
              <input type="submit" value="Отправить" />
          </form>
      </div>  
{% else %}
    <br /><h2>Благодарим за ваш отзыв</h2><br />
    <h3>Вы написали в отзыве следующее</h3>
    <ul>
        <li><span>Имя</span> {{ data.name }}</li>
        <li><span>Город</span> {{ data.city }}</li>
        <li><span>Пол</span> {{ data.gender }}</li>
        <li><span>Получать новостную рассылку</span> {{ data.notice }}</li>
        <li><span>Ваше мыло</span> {{ data.email }}</li>
        <li><span>Ваш отзыв</span> {{ data.message }}</li>
    </ul>
{% endif %}
<script>

    window.addEventListener("load", function () {
        $("#send_btn").mouseenter(function () {
            $("#send_btn").css('background', 'Orange');
        });

        $("#send_btn").mouseleave(function () {
            $("#send_btn").css('background', 'White');
        });
        
        $("#id_name").mouseenter(function () {
            $("#id_name").css('background', 'Orange');
        });

        $("#id_name").mouseleave(function () {
            $("#id_name").css('background', 'White');
        });

        $("#id_city").mouseenter(function () {
            $("#id_city").css('background', 'Orange');
        });

        $("#id_city").mouseleave(function () {
            $("#id_city").css('background', 'White');
        });

        $("#id_email").mouseenter(function () {
            $("#id_email").css('background', 'Orange');
        });

        $("#id_email").mouseleave(function () {
            $("#id_email").css('background', 'White');
        });

        $("#id_message").mouseenter(function () {
            $("#id_message").css('background', 'Orange');
        });

        $("#id_message").mouseleave(function () {
            $("#id_message").css('background', 'White');
        });
    });
</script>
{% endblock %}

Laba41/app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}
<h2>{{ title }}</h2>

{% for post in posts %}

<div>
    <h3>{{ post.title }}</h3>
    <h4>{{ post.posted }}</h4>
    <p>{{ post.description }}</p>
    <p><a href="{% url 'blogpost' parametr=post.id %}">Читать далее</a></p>
</div>

{% endfor %}

{% endblock %}

Laba41/app/templates/app/blogpost.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ post.title }}</h2><br />

{% if post.image and post.image.url != '/media/temp.jpg' %}
<img src="{{ post.image.url }}" alt="Картинка" width="300" height="200" />
{% endif %}

{% autoescape off %}
<p>{{ post.content|linebreaksbr }}</p>
{% endautoescape %}

{% if user.is_authenticated %}

<h3>Добавить комментарий</h3>
<form method="POST">
    {% csrf_token %}
    <div>
        {{ form.as_p }}
        <button type="submit" class="save btn-default">Отправить комментарий</button>
    </div>
</form>
{% else %}

<h3>Для добавления комментария, пожалуйста, авторизуйтесь</h3>

{% endif %}

{% for comment in comments %}
<h7>{{ comment.date }}</h7>
<h5>{{ comment.author }}</h5>
<p>{{  comment.text|linebreaksbr}}</p>
{% endfor %}

<p><a href="{% url 'blog' %}">Назад</a></p>
{% endblock %}

Laba41/app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
	Телефон:+7 (495) 984-53-83<br />
    E-mail: info@hobbyworld.ru<br />
	Адрес: 105005, Россия,  г. Москва, ул. Бауманская, д. 11, стр. 8<br />
</address>
{% endblock %}

Laba41/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}
<h2>{{ title }}.</h2>
<p>Сайт предоставляет информацию о интернет магазине Hobby World и наши контакты данные</p> 

<div class="slideshow-container">
    <div class="mySlides fade"><img class="photo-cell" src="{% static 'app/content/f1.jpeg' %}" /></div>
    <div class="mySlides fade"><img class="photo-cell" src="{% static 'app/content/f2.jpeg' %}" /></div>
    <div class="mySlides fade"><img class="photo-cell" src="{% static 'app/content/f3.jpeg' %}" /></div>

    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

</div>
<script>
    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        if (n > slides.length) { slideIndex = 1 }
        if (n < 1) { slideIndex = slides.length }
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slides[slideIndex - 1].style.display = "block";
    }
</script>

{% endblock %}

Laba41/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Мой проект</title>
    {% load static %}
    <link rel="icon" type="image/x-icon"   href="{% static 'app/content/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img src="{% static 'app/content/Hobby_World_logo.png' %}" width="30" height="30" alt="Logo 1"/> Hobby World</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Домашная страница</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Конктакты</a></li>
                    <li><a href="{% url 'link' %}">Ссылки</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавить статью</a></li>
                    {% endif %}
                    <li><a href="{% url 'anketa' %}">Отзыв</a></li>
                    {% if not user.is_authenticated %}
                    <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - Hobby World</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

Laba41/app/templates/app/link.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}

<h2>{{ title }}.</h2>

<a href ="https://www.mosigra.ru" target="_blank"> <img src="{% static 'app/content/unnamed.png' %}" width="200" height="200" alt="Logo 1"/></a>

<a href ="https://hobbygames.ru" target="_blank"> <img src="{% static 'app/content/загружено.png' %}" width="200" height="200" alt="Logo 2"/></a>

<a href ="https://hobbyworld.ru" target="_blank"> <img src="{% static 'app/content/cube.png' %}" width="200" height="200" alt="Logo 3"/></a>

{% endblock %}

Laba41/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте свой никнем для входа.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Ник</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Вхождение" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста введите корректные данные.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

Laba41/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Привет {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выходим</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Вхождение</a></li>
</ul>

{% endif %}

Laba41/app/templates/app/newpost.html
{% extends "app/layout.html" %}

{% block content %}

<h3>Добавить статью</h3>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ blogform.as_p }}
        <button type="submit" class="save btn-defult">Сохранить статью</button>
    </div>
</form>

{% endblock %}

Laba41/app/templates/app/registration.html
{% extends "app/layout.html" %}
{% block content %}
<h2>Регистрация пользователя</h2>
    <form method="POST"> {% csrf_token %}
        <div>
            {{ regform.as_p }}

            <button type="submit" class="save btn btn-default" >Зарегаться</button>
        </div>
    </form>
{% endblock %}

Laba41/app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2><br>

<video src="/media/p1.mp4" controls="controls" width="400" height="300" poster="/media/l1.jpg"></video>
<video src="/media/p2.mp4" controls="controls" width="400" height="300" poster="/media/l2.jpg"></video>
<video src="/media/p3.mp4" controls="controls" width="400" height="300" poster="/media/l3.jpg"></video>

{% endblock %}